version: '2'

services:

  server:
    image: webalyse/1click
    ports:
      - "11000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: oneclick
      POSTGRES_PASSWORD: oneclick
    ports:
      - "11001:5432"
    volumes:
      - 1click-postgres:/var/lib/postgresql/data

volumes:
  1click-postgres: